### ISSUE TITLE
I don't understand how update Internationalization 🤷‍♂️

### ISSUE THREAD

**Issue by Smartiiez** [solutelabs/horizontal_calendar#11]
Hi 👋,
First of all, **thank you** for your widget. It's exactly what I need.
I'm just stuck on the local date. My settings language device are set to French and my Region too.
 
I use ` Locale myLocale = Localizations.localeOf(context); print(myLocale);`to check the value.
Everything look like ok, but the date format don't change. 

Have you any ideas ?

**Comment by danilof** [comment]
@Smartiiez Hi, did you manage to solve Internationalization. I have the same problem and I am stuck also.
