### ISSUE TITLE
Add minSelectedDateCount parameter

### ISSUE THREAD

**Issue by dariof28** [solutelabs/horizontal_calendar#6]
Hi, and thanks for this beautiful widget.

I wanna ask you if could you add an optional `minSelectedDateCount` parameter to avoid the no-selected-dates situations (this would be useful in such situations where a selected date is always required, for example retrieve a list of items that mathes that day).

Right now I am able to initialize the `initialSelectedDates` but without this optional setting i am able to remove it by tapping on the element.

**Tip:**

```diff
@@ -149,1 +149,1 @@
-} else {
+} else if (selectedDates.lenght > widget.minSelectedDateCount ) {
  final isRemoved = selectedDates.remove(date);
  if (isRemoved && widget.onDateUnSelected != null) {
    widget.onDateUnSelected(date);
  }
}
```
Of course some validation should be added: 
```dart
assert(maxSelectedDateCount >= minSelectedDateCount);
assert(initialSelectedDates.lenght >= minSelectedDateCount);
[...]
```

**Comment by milind-mevada-stl** [comment]
Hi @dariof28 : Thanks for the suggestion. This is indeed a nice feature we would like to add. 

However, we are not able to give you the exact timeframe regarding when this feature will be added. It will be really appreciated if you can give a PR covering this feature.

Thanks.

**Comment by dariof28** [comment]
> Hi @dariof28 : Thanks for the suggestion. This is indeed a nice feature we would like to add.
> 
> However, we are not able to give you the exact timeframe regarding when this feature will be added. It will be really appreciated if you can give a PR covering this feature.
> 
> Thanks.

Sure! I'll work on it ASAP. Thanks
